#!/bin/bash

# If there are any files with the .swift extension, run swiftformat on them and add to the commit
git diff --diff-filter=d --staged --name-only | grep -e '\.swift$' | while read line; do
    swift run swiftformat "${line}" --quiet --config "Sources/PluginCore/Resources/default.swiftformat"
    git add "$line"
done
