#!/bin/bash

# TODO: Find a way to inject this command name.
command_name='kipple'

# Build the format command, telling it to detect and use modified files only.
# Once the command is complete, modified files are added back to the commit.
command="${command_name} format --staged-only --quiet"

if [ -z $(which $command_name) ]; then
    # Swift Package executable is not installed, so prepend "swift run" to the beginning of the command.
    command="swift run ${command}"
    # Echo a warning to the user.
    echo "${command_name} not installed. To speed up your pre-commit hook, run 'swift run ${command_name} install'."
fi

# Run the command
eval "$command"

# Wait for the jobs to finish.
# Source: https://linuxize.com/post/bash-wait/
wait
