#!/bin/bash

# Build the format command, telling it to detect and use modified files only.
# Once the command is complete, modified files are added back to the commit.
command='kipple format --staged-only --quiet'

if [ -z $(which kipple) ]; then
    # Swift Package executable is not installed, so prepend "swift run" to the beginning of the command.
    command="swift run ${command}"
    # Echo a warning to the user.
    echo 'Kipple not installed. To speed up your pre-commit hook, run 'swift run kipple install' from a KippleTools-enabled repository.'
fi

# Run the command
eval "$command"
