name: Swift Test (Vapor)

# Tests a Vapor website for Swift 5.6 (latest stable Vapor version) on macOS and Linux.

on:
  workflow_call:

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  swift_test_apple:
    uses: ./.github/workflows/swift_test_apple.yml
    needs: [prepare]
    with:
      xcode_version: 13.4
      platform: macOS
      build_method: swift
  swift_test_linux:
    uses: ./.github/workflows/swift_test_linux.yml
    needs: [prepare]
    with:
      swift_version: 5.6
  send_notifications:
    runs-on: ubuntu-latest
    needs: [swift_test_apple, swift_test_linux]
    if: failure()
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_CI_WEBHOOK }}
          title: Tests Failed
          status: Failure
          color: 0xff0000
