name: Swift Test (Vapor Package)

# Tests a Vapor package for Swift 5.5+ (for concurrency support) and greater on macOS and Linux.

on:
  workflow_call:

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  swift_test_apple:
    uses: ./.github/workflows/swift_test_apple.yml
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        xcode_version:
          - 13.2 # swift 5.5
          - 13.4 # swift 5.6
    with:
      xcode_version: ${{ matrix.xcode_version }}
      platform: macOS
      build_method: swift
  swift_test_linux:
    uses: ./.github/workflows/swift_test_linux.yml
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.5, 5.6]
    with:
      swift_version: ${{ matrix.swift_version }}
  send_notifications:
    runs-on: ubuntu-latest
    needs: [swift_test_apple, swift_test_linux]
    if: failure()
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_CI_WEBHOOK }}
          title: Tests Failed
          status: Failure
          color: 0xff0000
